# Sentiment Analysis

In [1]:
import numpy as np
import pandas as pd
import string
import nltk
from sklearn import preprocessing
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.model_selection import train_test_split
from nltk.corpus import stopwords
from nltk.stem.snowball import SnowballStemmer
from matplotlib import pyplot as plt
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

In [2]:
tweets = pd.read_csv("D:/STUDY/Datasets/twitter-data-on-abrogation-of-article-370/Tweets.csv")
tweets.head()

ID             datetime has_media  is_reply  is_retweet  \
0  1160091065472487424  2019-08-10 13:00:38       NaN     False       False   
1  1160065502200205312  2019-08-10 11:19:03       NaN     False       False   
2  1161366914007875584  2019-08-14 01:30:24       NaN      True       False   
3  1162074264301785088  2019-08-16 00:21:09       NaN      True       False   
4  1160566972569939969  2019-08-11 20:31:43       NaN      True       False   

  medias  nbr_favorite  nbr_reply  nbr_retweet  \
0    NaN           1.0        0.0          0.0   
1    NaN           0.0        0.0          0.0   
2    NaN           0.0        0.0          0.0   
3    NaN           0.0        0.0          0.0   
4    NaN           0.0        0.0          0.0   

                                                text  \
0  # KashmirWithModi \nWith the scrapping of  Art...   
1  Shocking & Shameful! A must read  article  for...   
2  What makes " True Islam followers" like you co...   
3  Just sickening to read this thread. I guess it...   
4  Don't worry Pyari Behna, whoever opposing or p...   

                                           url       user_id    usernameTweet  
0   /Hilladventure1/status/1160091065472487424  1.154411e+18   Hilladventure1  
1      /samwhitefyr/status/1160065502200205312  9.913207e+17      samwhitefyr  
2  /rashidakhan1977/status/1161366914007875584  7.105491e+17  rashidakhan1977  
3  /indianbyheart76/status/1162074264301785088  5.796150e+08  indianbyheart76  
4  /ShivaprakashYe2/status/1160566972569939969  1.134819e+18  ShivaprakashYe2

In [29]:
tweets.shape

(227259, 12)

In [3]:
tweets.isnull().sum()

ID                    0
datetime              0
has_media        190821
is_reply              0
is_retweet            0
medias           190821
nbr_favorite          0
nbr_reply             0
nbr_retweet           0
text                  0
url                   1
user_id               1
usernameTweet         1
dtype: int64

In [4]:
tweets = tweets.drop(['has_media','medias'],axis=1)

In [41]:
tweets.to_csv("tweets.csv")

In [6]:
tweets.head()

ID             datetime  is_reply  is_retweet  \
0  1160091065472487424  2019-08-10 13:00:38     False       False   
1  1160065502200205312  2019-08-10 11:19:03     False       False   
2  1161366914007875584  2019-08-14 01:30:24      True       False   
3  1162074264301785088  2019-08-16 00:21:09      True       False   
4  1160566972569939969  2019-08-11 20:31:43      True       False   

   nbr_favorite  nbr_reply  nbr_retweet  \
0           1.0        0.0          0.0   
1           0.0        0.0          0.0   
2           0.0        0.0          0.0   
3           0.0        0.0          0.0   
4           0.0        0.0          0.0   

                                                text  \
0  # KashmirWithModi \nWith the scrapping of  Art...   
1  Shocking & Shameful! A must read  article  for...   
2  What makes " True Islam followers" like you co...   
3  Just sickening to read this thread. I guess it...   
4  Don't worry Pyari Behna, whoever opposing or p...   

                                           url       user_id    usernameTweet  
0   /Hilladventure1/status/1160091065472487424  1.154411e+18   Hilladventure1  
1      /samwhitefyr/status/1160065502200205312  9.913207e+17      samwhitefyr  
2  /rashidakhan1977/status/1161366914007875584  7.105491e+17  rashidakhan1977  
3  /indianbyheart76/status/1162074264301785088  5.796150e+08  indianbyheart76  
4  /ShivaprakashYe2/status/1160566972569939969  1.134819e+18  ShivaprakashYe2

In [7]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

In [8]:
senti = SentimentIntensityAnalyzer()

In [9]:
# Creating a function

text_polar = lambda x: senti.polarity_scores(x)['compound']

In [11]:
tweets['Polarity_score'] = tweets['text'].apply(text_polar)

tweets.head()

ID             datetime  is_reply  is_retweet  \
0  1160091065472487424  2019-08-10 13:00:38     False       False   
1  1160065502200205312  2019-08-10 11:19:03     False       False   
2  1161366914007875584  2019-08-14 01:30:24      True       False   
3  1162074264301785088  2019-08-16 00:21:09      True       False   
4  1160566972569939969  2019-08-11 20:31:43      True       False   

   nbr_favorite  nbr_reply  nbr_retweet  \
0           1.0        0.0          0.0   
1           0.0        0.0          0.0   
2           0.0        0.0          0.0   
3           0.0        0.0          0.0   
4           0.0        0.0          0.0   

                                                text  \
0  # KashmirWithModi \nWith the scrapping of  Art...   
1  Shocking & Shameful! A must read  article  for...   
2  What makes " True Islam followers" like you co...   
3  Just sickening to read this thread. I guess it...   
4  Don't worry Pyari Behna, whoever opposing or p...   

                                           url       user_id    usernameTweet  \
0   /Hilladventure1/status/1160091065472487424  1.154411e+18   Hilladventure1   
1      /samwhitefyr/status/1160065502200205312  9.913207e+17      samwhitefyr   
2  /rashidakhan1977/status/1161366914007875584  7.105491e+17  rashidakhan1977   
3  /indianbyheart76/status/1162074264301785088  5.796150e+08  indianbyheart76   
4  /ShivaprakashYe2/status/1160566972569939969  1.134819e+18  ShivaprakashYe2   

   Polarity_score  
0          0.5859  
1         -0.7500  
2          0.6860  
3         -0.4895  
4          0.2514

In [14]:
text = tweets[['text','Polarity_score']]

In [15]:
text.head()

text  Polarity_score
0  # KashmirWithModi \nWith the scrapping of  Art...          0.5859
1  Shocking & Shameful! A must read  article  for...         -0.7500
2  What makes " True Islam followers" like you co...          0.6860
3  Just sickening to read this thread. I guess it...         -0.4895
4  Don't worry Pyari Behna, whoever opposing or p...          0.2514

In [16]:
# Categorizing the polarity range
sentiment_mapping = {1 : "Very Bad", 2 : "Bad", 3 : "Neutral", 4 : "Good", 5 : "Very Good"}

map_sentiment = lambda val : np.digitize(val, [-1, -0.8, -0.25, 0.25, 0.8])

In [17]:
text['Sentiment_category'] = text['Polarity_score'].apply(map_sentiment)

# Labeling the sentiment category

text['Label'] = text['Sentiment_category'].map(sentiment_mapping)

text.head()

C:\Users\anura\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\anura\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """


text  Polarity_score  \
0  # KashmirWithModi \nWith the scrapping of  Art...          0.5859   
1  Shocking & Shameful! A must read  article  for...         -0.7500   
2  What makes " True Islam followers" like you co...          0.6860   
3  Just sickening to read this thread. I guess it...         -0.4895   
4  Don't worry Pyari Behna, whoever opposing or p...          0.2514   

   Sentiment_category Label  
0                   4  Good  
1                   2   Bad  
2                   4  Good  
3                   2   Bad  
4                   4  Good

In [19]:
text.to_csv("sentiment_analysis_article370.csv")

In [21]:
# Creating the test and training data

X = text['text']

Y = text['Label']

X_train, X_test, Y_train, Y_test = train_test_split(X,Y , test_size = 0.2 , random_state = 1234)


In [22]:
X_train.shape , Y_train.shape

((181807,), (181807,))

In [23]:
# Creatin a DTM 

vec = TfidfVectorizer()

X_train_vect =vec.fit_transform(X_train)

X_train_vect

<181807x144882 sparse matrix of type '<class 'numpy.float64'>'
	with 4541011 stored elements in Compressed Sparse Row format>

In [24]:
# Build a Model

from sklearn.naive_bayes import MultinomialNB

nb_model = MultinomialNB()

In [25]:
# Fitting the model on X_train_vect and Y_train

nb_model.fit(X_train_vect,Y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [26]:
X_test_vect = vec.transform(X_test)

X_test_vect

<45452x144882 sparse matrix of type '<class 'numpy.float64'>'
	with 1108336 stored elements in Compressed Sparse Row format>

In [27]:
Y_Pred = nb_model.predict(X_test_vect)

Y_Pred

array(['Neutral', 'Good', 'Good', ..., 'Good', 'Good', 'Good'],
      dtype='<U9')

In [28]:
Y_train.value_counts()

Neutral      68321
Good         62000
Bad          31815
Very Good    14431
Very Bad      5240
Name: Label, dtype: int64

In [30]:
# This shows that most of the tweets are Positive in Nature.

In [31]:
from sklearn.metrics import accuracy_score , confusion_matrix

accuracy_score(Y_test , Y_Pred)

0.5731760978614803

In [32]:
confusion_matrix(Y_test , Y_Pred)

array([[ 1047,  2868,  3983,     0,     0],
       [   42, 12592,  2835,     0,     0],
       [  118,  4692, 12406,     0,     1],
       [  445,   396,   414,     0,     0],
       [    3,  3533,    70,     0,     7]], dtype=int64)

In [62]:
from sklearn.ensemble import RandomForestClassifier

In [63]:
clf = RandomForestClassifier(n_estimators=100)

## Topic modelling

In [42]:
from sklearn.decomposition import LatentDirichletAllocation

In [43]:
# Lets take the reviews.text column from the data
text = tweets[["text"]]
print(text['text'][0])

# KashmirWithModi 
With the scrapping of  Article   370 , the dream of Sardar Patel, Baba Saheb Ambedkar, Dr Syama Prasad Mukherjee, Atalji and of crores of patriots has been fulfilled. 
@aajtak  @RepMarkMeadows  @TheNationalUAE  @CovfefeKatie pic.twitter.com/ARxmbYfwww


In [44]:
# Step 1 : Convert every thing into lower case

text['Clean_text'] = text['text'].str.lower().str.replace('[^a-z ]', '')
print(text['Clean_text'][0])

 kashmirwithmodi with the scrapping of  article     the dream of sardar patel baba saheb ambedkar dr syama prasad mukherjee atalji and of crores of patriots has been fulfilled aajtak  repmarkmeadows  thenationaluae  covfefekatie pictwittercomarxmbyfwww


C:\Users\anura\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [45]:
# Step 2: Remove stop words

stop = set(stopwords.words('english'))

def sw(text):
    text = [word for word in text.split() if word not in stop]
    return " ".join(text)

text['Split_words'] = text['Clean_text'].apply(sw)

print(text['Split_words'][0])

kashmirwithmodi scrapping article dream sardar patel baba saheb ambedkar dr syama prasad mukherjee atalji crores patriots fulfilled aajtak repmarkmeadows thenationaluae covfefekatie pictwittercomarxmbyfwww


C:\Users\anura\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':


In [46]:
text.head()

text  \
0  # KashmirWithModi \nWith the scrapping of  Art...   
1  Shocking & Shameful! A must read  article  for...   
2  What makes " True Islam followers" like you co...   
3  Just sickening to read this thread. I guess it...   
4  Don't worry Pyari Behna, whoever opposing or p...   

                                          Clean_text  \
0   kashmirwithmodi with the scrapping of  articl...   
1  shocking  shameful a must read  article  for e...   
2  what makes  true islam followers like you conf...   
3  just sickening to read this thread i guess it ...   
4  dont worry pyari behna whoever opposing or pro...   

                                         Split_words  
0  kashmirwithmodi scrapping article dream sardar...  
1  shocking shameful must read article everyone e...  
2  makes true islam followers like conflate faith...  
3  sickening read thread guess doesnt matter arti...  
4  dont worry pyari behna whoever opposing protes...

In [47]:
# Create a DTM with Tfidf vectorizer

vect = TfidfVectorizer()

DTM = vect.fit_transform(text['Split_words'])

DTM

<227259x225566 sparse matrix of type '<class 'numpy.float64'>'
	with 3419794 stored elements in Compressed Sparse Row format>

In [48]:
# Model 

lda = LatentDirichletAllocation(n_components=5 , max_iter= 10)

lda_output = lda.fit_transform(DTM)

print(lda_output)


[[0.03744353 0.03747539 0.03751085 0.84977807 0.03779215]
 [0.04072172 0.04076204 0.83707548 0.04072533 0.04071543]
 [0.03448722 0.03447951 0.86198917 0.03458052 0.03446358]
 ...
 [0.04402916 0.04393707 0.72006633 0.1480181  0.04394934]
 [0.0426109  0.5162613  0.35332004 0.04586665 0.04194111]
 [0.82264774 0.04376823 0.04499415 0.04477351 0.04381637]]


In [49]:
lda_output.shape

(227259, 5)

In [52]:
# Document Topic Matrix
topicname = ['Topic' + str(i) for i in range(lda.n_components)]

docname = ['Doc' + str(i) for i in range(DTM.shape[0])] 

In [53]:
df_documemt_topic = pd.DataFrame(np.round(lda_output,2) , columns=topicname, index = docname)

df_documemt_topic.head()

Topic0  Topic1  Topic2  Topic3  Topic4
Doc0    0.04    0.04    0.04    0.85    0.04
Doc1    0.04    0.04    0.84    0.04    0.04
Doc2    0.03    0.03    0.86    0.03    0.03
Doc3    0.04    0.04    0.86    0.04    0.04
Doc4    0.04    0.04    0.34    0.50    0.08

In [54]:
dominating_topic = np.argmax(df_documemt_topic.values, axis = 1)
dominating_topic

array([3, 2, 2, ..., 2, 1, 0], dtype=int64)

In [55]:
df_documemt_topic['Dom_topic'] = dominating_topic
df_documemt_topic.head()

Topic0  Topic1  Topic2  Topic3  Topic4  Dom_topic
Doc0    0.04    0.04    0.04    0.85    0.04          3
Doc1    0.04    0.04    0.84    0.04    0.04          2
Doc2    0.03    0.03    0.86    0.03    0.03          2
Doc3    0.04    0.04    0.86    0.04    0.04          2
Doc4    0.04    0.04    0.34    0.50    0.08          3

In [56]:
df_documemt_topic['Dom_topic'].value_counts()

2    112833
3     59683
0     19509
1     18407
4     16827
Name: Dom_topic, dtype: int64

In [57]:
lda.components_

array([[ 2.47919522,  0.7620028 ,  0.20001678, ...,  0.47354072,
         0.22526698,  0.20001689],
       [10.1055733 ,  0.20397085,  0.45339808, ...,  0.20001798,
         0.20022366,  0.20001805],
       [ 8.81728745,  0.20360718,  0.20113121, ...,  0.20050628,
         0.46707223,  0.20000571],
       [19.23250098,  0.54869431,  0.20000878, ...,  0.20000819,
         0.25746636,  0.20174627],
       [ 1.2492748 ,  0.4885806 ,  0.20001601, ...,  0.2000196 ,
         0.20018905,  0.51009494]])

In [58]:
# Creating the dataframe between topic and terms

df_topic_keywords = pd.DataFrame(lda.components_)

df_topic_keywords

0         1         2         3         4         5         6       \
0   2.479195  0.762003  0.200017  0.200104  0.531961  0.599317  0.200050   
1  10.105573  0.203971  0.453398  0.200120  0.200040  0.200025  0.200077   
2   8.817287  0.203607  0.201131  1.142218  0.203971  0.200008  0.204974   
3  19.232501  0.548694  0.200009  0.200055  0.200022  0.201207  0.539241   
4   1.249275  0.488581  0.200016  0.200115  0.200041  0.200023  0.200085   

     7         8         9       ...    225556    225557    225558    225559  \
0  0.200080  0.200080  0.200042  ...  0.200016  0.645003  0.200025  0.796450   
1  0.200078  0.200078  0.200045  ...  0.200017  0.200020  0.618463  0.240306   
2  0.818722  0.818722  0.519868  ...  0.200005  0.200008  0.202491  0.529128   
3  0.200058  0.200058  0.200022  ...  4.477813  0.200010  0.200015  0.200065   
4  0.200075  0.200075  0.200046  ...  0.200017  0.200020  0.200028  0.574931   

     225560    225561    225562    225563    225564    225565  
0  0.200021  0.200011  1.840798  0.473541  0.225267  0.200017  
1  0.200021  0.453446  0.200025  0.200018  0.200224  0.200018  
2  0.202019  0.200004  0.201918  0.200506  0.467072  0.200006  
3  0.200011  0.200007  0.200895  0.200008  0.257466  0.201746  
4  0.448958  0.200013  0.200025  0.200020  0.200189  0.510095  

[5 rows x 225566 columns]

In [59]:
# Naming the Columns and Rows

df_topic_keywords.columns = vect.get_feature_names()

df_topic_keywords.index = topicname

df_topic_keywords

aa       aaa      aaaa     aaaaa  aaaaaaaaaaaaa  \
Topic0   2.479195  0.762003  0.200017  0.200104       0.531961   
Topic1  10.105573  0.203971  0.453398  0.200120       0.200040   
Topic2   8.817287  0.203607  0.201131  1.142218       0.203971   
Topic3  19.232501  0.548694  0.200009  0.200055       0.200022   
Topic4   1.249275  0.488581  0.200016  0.200115       0.200041   

        aaaaaaaaaaaaaaaaaaaaaaaaaa  aaaaaaaaaathhooooooo  aaaaaaattttt  \
Topic0                    0.599317              0.200050      0.200080   
Topic1                    0.200025              0.200077      0.200078   
Topic2                    0.200008              0.204974      0.818722   
Topic3                    0.201207              0.539241      0.200058   
Topic4                    0.200023              0.200085      0.200075   

        aaaaaaatttttkashmirhamarahai  aaaaaand  ...  \
Topic0                      0.200080  0.200042  ...   
Topic1                      0.200078  0.200045  ...   
Topic2                      0.818722  0.519868  ...   
Topic3                      0.200058  0.200022  ...   
Topic4                      0.200075  0.200046  ...   

        zxtcwsvmxzbrjxqwtntdkbhscppbcmeytnhzoqxniipwhplmjdvpdiokvk        zy  \
Topic0                                           0.200016           0.645003   
Topic1                                           0.200017           0.200020   
Topic2                                           0.200005           0.200008   
Topic3                                           4.477813           0.200010   
Topic4                                           0.200017           0.200020   

          zyaada     zyada     zyadi      zyda  \
Topic0  0.200025  0.796450  0.200021  0.200011   
Topic1  0.618463  0.240306  0.200021  0.453446   
Topic2  0.202491  0.529128  0.202019  0.200004   
Topic3  0.200015  0.200065  0.200011  0.200007   
Topic4  0.200028  0.574931  0.448958  0.200013   

        zzamitshahonarticlejammuandkashmir  \
Topic0                            1.840798   
Topic1                            0.200025   
Topic2                            0.201918   
Topic3                            0.200895   
Topic4                            0.200025   

        zzmanishtewarishadesofgreycommenttwitterreacts  \
Topic0                                        0.473541   
Topic1                                        0.200018   
Topic2                                        0.200506   
Topic3                                        0.200008   
Topic4                                        0.200020   

        zztmkrishnarespondstojammukashmircrisiswithpoetry     zzwts  
Topic0                                           0.225267  0.200017  
Topic1                                           0.200224  0.200018  
Topic2                                           0.467072  0.200006  
Topic3                                           0.257466  0.201746  
Topic4                                           0.200189  0.510095  

[5 rows x 225566 columns]

In [60]:
#  Finding The top 20 words for each topic

def show_topic(vect , lda , n_words):
    keywords = np.array(vect.get_feature_names())
    topic_keywords = []
    for topic_weights in lda.components_:
        topic_keywords_locs = (-topic_weights).argsort()[:n_words]
        topic_keywords.append(keywords.take(topic_keywords_locs))
    return topic_keywords

topic_keywords = show_topic(vect = vect , lda=lda , n_words=20)
topic_keywords

[array(['article', 'kashmir', 'https', 'httpswww', 'india', 'pakistan',
        'says', 'revoked', 'jammuandkashmir', 'articlerevoked', 'indian',
        'every', 'news', 'jammu', 'kashmirhamarahai', 'internal', 'jk',
        'status', 'matter', 'like'], dtype='<U430'),
 array(['article', 'https', 'httpswww', 'kashmir', 'via', 'aindia', 'news',
        'special', 'status', 'bbc', 'india', 'bbccomnewsworldasi',
        'youtube', 'bbccouknewsworldasi',
        'economictimesindiatimescomnewspolitics', 'http', 'jk', 'scrapped',
        'hai', 'scrapping'], dtype='<U430'),
 array(['article', 'kashmir', 'india', 'people', 'https', 'indian',
        'pakistan', 'jk', 'dont', 'kashmiri', 'state', 'like', 'know',
        'congress', 'abrogation', 'kashmiris', 'govt', 'constitution',
        'even', 'scrapping'], dtype='<U430'),
 array(['article', 'amitshah', 'narendramodi', 'one', 'india', 'kashmir',
        'historic', 'kashmirhamarahai', 'ji', 'modi', 'scrapped', 'jammu',
        'day', 'ja

In [61]:
# Creating a DataFrame

df_topic_keywords = pd.DataFrame(topic_keywords)
df_topic_keywords

0         1             2         3      4         5         6   \
0  article   kashmir         https  httpswww  india  pakistan      says   
1  article     https      httpswww   kashmir    via    aindia      news   
2  article   kashmir         india    people  https    indian  pakistan   
3  article  amitshah  narendramodi       one  india   kashmir  historic   
4  article     https      httpswww       via   http   kashmir  congress   

                 7                8               9         10  \
0           revoked  jammuandkashmir  articlerevoked    indian   
1           special           status             bbc     india   
2                jk             dont        kashmiri     state   
3  kashmirhamarahai               ji            modi  scrapped   
4               bjp            jammu            says      amit   

                   11       12                   13  \
0               every     news                jammu   
1  bbccomnewsworldasi  youtube  bbccouknewsworldasi   
2                like     know             congress   
3               jammu      day      jammuandkashmir   
4            scrapped     modi                  jdu   

                                       14               15        16  \
0                        kashmirhamarahai         internal        jk   
1  economictimesindiatimescomnewspolitics             http        jk   
2                              abrogation        kashmiris      govt   
3                                decision  congratulations     union   
4                                   india             shah  pakistan   

             17      18         19  
0        status  matter       like  
1      scrapped     hai  scrapping  
2  constitution    even  scrapping  
3      minister     jai         jk  
4          govt  status    special